theme: minima
title: When the day is not enough
author: Chambras
email: marcech.am@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal technical blog

# social links
twitter_username: @ch4mbr4s
github_username:  chambras

show_excerpts: true # set to false to remove excerpts on the homepage
